apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: pokemon-site
        image: lisetterz/pokemon:pokemonImg
---
apiVersion: v1
kind: Service
metadata:
  name: pokemon-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001